Декаративные элементы страницы каталога
htmlacademy-htmlcss/1367209-technomart-29 pull request #10
Opened 2020-10-27 10:15 UTC by HuvosFromDarnassus

- Без форм
- Без pixel perfect

2020-10-27 21:36 UTC, raccoonroman requested changes

2020-10-27 21:36 UTC, raccoonroman commented on catalog.html
> +                <a class="product-sort-link product-sort-more sortActive" href="">
_названия классов должны быть оформлены единообразно_
https://up.htmlacademy.ru/htmlcss/29/criteries#b15
если слова разделяются с помощью дефиса, то так должно быть везде
```suggestion
                <a class="product-sort-link product-sort-more sort-active" href="">
```

2020-10-27 21:36 UTC, raccoonroman commented on catalog.html
> +                  <svg width="12" height="10" fill="none" xmlns="http://www.w3.org/2000/svg">
xmlns можно в разметке удалять
```suggestion
                  <svg width="12" height="10" fill="none">
```

2020-10-27 21:36 UTC, raccoonroman commented on catalog.html
> +                    <path d="M5.66241 10L0.162415 0H11.1624" fill="#C5C5C5" />
```suggestion
                  <svg width="12" height="10" viewBox="0 0 12 10" fill="#C5C5C5" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.66241 10L0.162415 0H11.1624" />
```

2020-10-27 21:36 UTC, raccoonroman commented on catalog.html
> +      <button class="button cart-checkout-button" type="button">Оформить заказ</button>
это не форма, просто две кнопки

2020-10-27 21:36 UTC, raccoonroman commented on css/style.css
> +.authorized-user::after {
это две отдельные ссылки - профиля и выхода https://prnt.sc/v88cnp

2020-10-27 21:36 UTC, raccoonroman commented on css/style.css
> +  right: -39px;
```suggestion
  left: 100%;
```

2020-10-28 06:11 UTC, HuvosFromDarnassus commented on catalog.html
> +                <a class="product-sort-link product-sort-more sortActive" href="">
Исправлено

2020-10-28 06:12 UTC, HuvosFromDarnassus commented on catalog.html
> +                  <svg width="12" height="10" fill="none" xmlns="http://www.w3.org/2000/svg">
Исправлено

2020-10-28 06:13 UTC, HuvosFromDarnassus commented on catalog.html
> +                    <path d="M5.66241 10L0.162415 0H11.1624" fill="#C5C5C5" />
Исправлено

2020-10-28 06:14 UTC, HuvosFromDarnassus commented on catalog.html
> +      <button class="button cart-checkout-button" type="button">Оформить заказ</button>
Исправлено

2020-10-28 06:14 UTC, HuvosFromDarnassus commented on css/style.css
> +  right: -39px;
Исправлено

2020-10-28 06:33 UTC, HuvosFromDarnassus commented on css/style.css
> +.authorized-user::after {
Исправлено

2020-10-28 17:08 UTC, raccoonroman requested changes

2020-10-28 17:08 UTC, raccoonroman commented on css/style.css
> +  position: absolute;
во-первых, ссылки не должны быть абсолютом одна на другой. Во-вторых, при наведении на зону ссылки выхода, ссылка должна быть на станицу выхода, а не профиля юзера. https://prnt.sc/v8tdu7
Я в предыдущем топике замечаний на скрине показал размеры ссылок https://prnt.sc/v88cnp

2020-10-29 06:33 UTC, HuvosFromDarnassus commented on catalog.html
> +    <div class="modal-cart-bottom" action="" method="post">
Исправлено

2020-10-29 07:24 UTC, HuvosFromDarnassus commented on css/style.css
> +  position: absolute;
Исправлено

2020-10-29 07:50 UTC, raccoonroman approved these changes

2020-10-29 07:50 UTC, merged