Оформление страницы каталога
htmlacademy-htmlcss/1367209-technomart-29 pull request #12
Opened 2020-11-03 17:32 UTC by HuvosFromDarnassus

1) Нужна помощь с hover и active для чекбоксов и радио в фильтре товара (не знаю как для псевдо-элмента лучше сделать ховер и эктив), если можно дайте подсказку

2) Не знаю как лучше сделать появляющиеся кнопки при наведении на карточку товара, тоже нужна помощь

2020-11-03 21:38 UTC, raccoonroman requested changes

2020-11-03 21:38 UTC, raccoonroman commented on catalog.html
> +            <fieldset class="filter-producers">
у fieldset-ов стилизация должна быть одинаковая и классы тоже, названия которых никак не зависят от того, какие элементы внутри этой формы

2020-11-03 21:38 UTC, raccoonroman commented on catalog.html
> +            <fieldset class="filter-power-supply">
нужно сделать одинаковый класс для всех fieldset-ов этой формы

2020-11-03 21:38 UTC, raccoonroman commented on css/style.css
> +  left: 99%;
правильно было радиус с правой стороны у `product-card-price` убрать

2020-11-03 21:38 UTC, raccoonroman commented on css/style.css
> +  box-sizing: content-box;
это внесет только путаницу. Потом запросто можно забыть, что здесь используется другая модель расчета размеров. Используй всегда border-box.

2020-11-03 21:38 UTC, raccoonroman commented on css/style.css
> +  left: -45px;
left должно быть со значением 0. Псевдоэлемент принадлежит своему родителю, и когда он выходит за его границы (когда минусовое значение), верстку труднее контролировать. Может случиться так, что псевдоэлемент может налезть на другие элементы или вообще вылезть за границы вьюпорта, если например делается адаптив для мобилки. 
Кстати, вот здесь немного про это написано, только на примере радиокнопок : https://isqua.ru/blog/2016/06/19/crash-test-viorstki/

В итоге, в псевдоэлемента не должны быть отрицательные значения (left, top и т.д.). Для этого лейблу нужно задать паддинги.

2020-11-03 21:38 UTC, raccoonroman commented on css/style.css
> +.filter-input-checkbox + .filter-label::before:hover {
можно просто вот так:
```suggestion
.filter-label:hover::before {
```

2020-11-03 21:38 UTC, raccoonroman commented on css/style.css
> +  background-image: url("../img/filter-checkbox-checked-icon.svg");
должен быть пробел между галкой и квадратом https://prnt.sc/vcvini

2020-11-03 21:38 UTC, raccoonroman commented on css/style.css
> +  transform: translateY(-34%);
```suggestion
  top: 50%;
  transform: translateY(-50%);
```

и у ::before тоже

2020-11-03 21:38 UTC, raccoonroman commented on css/style.css
> +  left: -21%;
положительное значение должно быть, плюс здесь лучше пикселями чем процентами

2020-11-03 21:38 UTC, raccoonroman commented on css/style.css
> +  position: absolute;
```suggestion
  position: fixed;
```

попап должен быть по центру относительно экрана

2020-11-04 12:51 UTC, HuvosFromDarnassus commented on catalog.html
> +          <form class="filter-price-slider" action="https://echo.htmlacademy.ru" method="get">
Исправлено

2020-11-04 12:52 UTC, HuvosFromDarnassus commented on catalog.html
> +                  <input class="max-price" type="number" name="mxa-price" value="30000">
Исправлено

2020-11-04 12:53 UTC, HuvosFromDarnassus commented on catalog.html
> +          <form class="filter" method="get" action="https://echo.htmlacademy.ru">
Исправлено

2020-11-04 12:56 UTC, HuvosFromDarnassus commented on catalog.html
> +            <fieldset class="filter-producers">
Исправлено

2020-11-04 12:56 UTC, HuvosFromDarnassus commented on catalog.html
> +            <fieldset class="filter-power-supply">
Исправлено

2020-11-04 12:59 UTC, HuvosFromDarnassus commented on css/style.css
> +  left: 99%;
Исправлено

2020-11-04 13:00 UTC, HuvosFromDarnassus commented on css/style.css
> +  box-sizing: content-box;
Исправлено

2020-11-04 13:08 UTC, HuvosFromDarnassus commented on css/style.css
> +  left: -45px;
Исправлено

2020-11-04 14:21 UTC, HuvosFromDarnassus commented on css/style.css
> +.filter-input-checkbox + .filter-label::before:hover {
Исправлено

2020-11-04 14:51 UTC, HuvosFromDarnassus commented on css/style.css
> +  background-image: url("../img/filter-checkbox-checked-icon.svg");
Исправлено (Добавил в редакторе svg белый пробел на кончики галочки, костыли конечно)

2020-11-04 14:52 UTC, HuvosFromDarnassus commented on css/style.css
> +  transform: translateY(-34%);
Исправлено

2020-11-04 14:52 UTC, HuvosFromDarnassus commented on css/style.css
> +  left: -21%;
Исправлено

2020-11-04 14:56 UTC, HuvosFromDarnassus commented on css/style.css
> +  position: absolute;
Исправлено

2020-11-04 15:05 UTC, HuvosFromDarnassus commented on catalog.html
> +                  <span class="price-del">-</span>
Не разобрался как псевдо-элементов вывести.

2020-11-04 21:26 UTC, raccoonroman commented on css/style.css
> +  background-image: url("../img/filter-checkbox-checked-icon.svg");
та просто можно было ивлечь иконку с фигмы

2020-11-04 21:27 UTC, raccoonroman commented on css/style.css
> +  background-image: url("../img/filter-checkbox-checked-icon.svg");
квадрат с галкой - как одна иконка

2020-11-04 21:36 UTC, raccoonroman approved these changes

2020-11-04 21:36 UTC, merged