Завершил разметку главной страницы
htmlacademy-htmlcss/1367209-technomart-29 pull request #2
Opened 2020-09-12 16:19 UTC by HuvosFromDarnassus

2020-09-13 09:47 UTC, HuvosFromDarnassus reviewed
Указал возможные ошибки и моменты, в которых не уверен.

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +      <h1><a href="index.html">Техномарт</a></h1>
В макете техномарта не совсем понятно, что делать с логотипом.
Изображение, которое необходимо скачать и вставить картинкой в HTML 
или пока вставаить заголовок и потом с помощью стилей сделать как на
макете?

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +    <header>
Разделить ли центральную часть header на section для:
курсивной фразы, телефона с адрессом и кнопок войти и регистрация?

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +        <!-- Карусель категорий товаров -->
Не уверен, что правильно разметил будущий карусель

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +        <!-- Список карточек товаров -->
Не уверен, что правильно разметил карточки товаров

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +        <!-- Список ссылок-переключателей -->
Не уверен как правильно разметить
переключатели в секции "Сервисы" (Доставка, гарантия, кредит).

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +      <h1><a href="index.html">Техномарт</a></h1>
Повторно использовал h1 для футера. Не понятно, как разметить главный логотип сайта

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +      <!-- Основное меню в футере навигационное меню -->
Здесь скорее всего семантическая ошибка - повторно использовал nav для футера

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +      <!-- Список ссылок на услуги -->
Не до конца уверен, правильно ли разметил ссылки. (Последний пункт в
требованиях к домашнему заданию)

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +        <!-- Список товаров и услуг -->
Не уверен что правильно разметил
карточки-ссылки 'Товаров и услуг'.

2020-09-13 09:47 UTC, HuvosFromDarnassus commented on index.html
> +      <!-- Основное меню -->
Являются ли кнопки: войти и регистрация - частью
основного меню nav?

2020-09-13 17:58 UTC, raccoonroman commented on index.html
> +        <!-- Карусель категорий товаров -->
если в чем-то не уверен, можно обсудить это на консультации

2020-09-13 18:05 UTC, raccoonroman commented on index.html
> +    <header>
на section это не сильно похоже, я бы сделал дивом

2020-09-13 18:06 UTC, raccoonroman commented on index.html
> +      <h1><a href="index.html">Техномарт</a></h1>
пока сделать ссылкой и внутри нее заглушку под картинку, как написано в задании

2020-09-13 18:07 UTC, raccoonroman commented on index.html
> +      <h1><a href="index.html">Техномарт</a></h1>
создавайте пожалуйста заявки и все вопросы пишите на консультации

2020-09-13 18:09 UTC, raccoonroman commented on index.html
> +      <h1><a href="index.html">Техномарт</a></h1>
здесь не нужен h1. Должна быть ссылка, внутри которой векторное изображение. Пока пусть будет текст.

2020-09-13 19:03 UTC, raccoonroman requested changes
В целом гуд. Где комментарии не оставлял, значит сделано хорошо. Или пока хорошо. Наперед желательно не забегать и делать по заданию только то, что требуется. Задания так расписаны, чтобы покрыть всю работу, которая требуется над проектом. И по поводу картинок - https://up.htmlacademy.ru/htmlcss/29/criteries#b14 . Картинки должны быть названы английскими словами в нижнем регистре.

2020-09-14 16:05 UTC, HuvosFromDarnassus commented on index.html
> +      <h1><a href="index.html">Техномарт</a></h1>
Исправлено

2020-09-14 16:05 UTC, HuvosFromDarnassus commented on index.html
> +    <header>
Исправлено

2020-09-14 16:05 UTC, HuvosFromDarnassus commented on index.html
> +      <h1><a href="index.html">Техномарт</a></h1>
Исправлено

2020-09-14 16:05 UTC, HuvosFromDarnassus commented on catalog.html
> +<html lang="en">
Исправлено

2020-09-14 16:06 UTC, HuvosFromDarnassus commented on index.html
> +      >
Исправлено

2020-09-14 16:06 UTC, HuvosFromDarnassus commented on index.html
> +          Телефон:+7 (812) 555-05-55<br />
Исправлено

2020-09-14 16:06 UTC, HuvosFromDarnassus commented on index.html
> +          Адресс:г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8
Исправлено

2020-09-14 16:06 UTC, HuvosFromDarnassus commented on index.html
> +          ><img src="img/map-preview.png" alt="Карта" width="300" height="158"
Исправлено

2020-09-14 16:06 UTC, HuvosFromDarnassus commented on index.html
> +        г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8<br />
Исправлено

2020-09-14 16:06 UTC, HuvosFromDarnassus commented on index.html
> +        +7 (812) 555-05-55
Исправлено

2020-09-14 16:06 UTC, HuvosFromDarnassus commented on index.html
> +      <section>
Исправлено

2020-09-14 16:06 UTC, HuvosFromDarnassus commented on index.html
> +        Обратная связь:<br />
Исправлено

2020-09-14 19:46 UTC, raccoonroman requested changes

2020-09-14 19:46 UTC, raccoonroman commented on index.html
> +          >Интернет-магазин строительных материалов и инструментов для
если это только обертка для текста, то лучше сделать абзацом вместо дива.

2020-09-14 19:46 UTC, raccoonroman commented on index.html
> +            <a href=""><p>На любой вкус</p></a>
не нужно текст оборачивать в абзац, достаточно просто ссылки.

2020-09-14 19:46 UTC, raccoonroman commented on index.html
> +                  src="https://via.placeholder.com/620x266"
повторюсь, [изображение декоративное](https://htmlacademy.ru/blog/boost/graphics/content-or-decor-img), соответственно нужно убрать из разметки. В будущем его нужно вывести через стили.

2020-09-14 19:46 UTC, raccoonroman commented on index.html
> +                <button type="button" disabled>Назад</button>
кнопки не являются частью списка слайдов. Они должны быть на одном уровне со списком. Можно сделать еще контейнер (див) для слайдера. Внутри него список слайдов + навигация (стрелки и точки). Сам контейнер поместить в лишку, внутри которой сейчас лежит список. При таком подходе удобно переиспользовать слайдер. Можно будет просто скопировать размеку слайдера (контейнер) и использовать в другом месте.

2020-09-14 19:46 UTC, raccoonroman commented on index.html
> +      <!-- Основное меню в футере навигационное меню -->
тег nav можно использовать несколько раз

2020-09-15 14:12 UTC, HuvosFromDarnassus commented on index.html
> +          >Интернет-магазин строительных материалов и инструментов для
Исправил

2020-09-15 14:12 UTC, HuvosFromDarnassus commented on index.html
> +            <a href=""><p>На любой вкус</p></a>
Исправил

2020-09-15 14:12 UTC, HuvosFromDarnassus commented on index.html
> +                <button type="button" disabled>Назад</button>
Исправил

2020-09-15 18:54 UTC, raccoonroman requested changes
Вторая страница размечена хорошо 👍 . Нужно лишь немного доработать

2020-09-15 18:54 UTC, raccoonroman commented on catalog.html
> +        <a href="">Равшан Джамшутович</a>
это 2 отдельные ссылки https://prnt.sc/uhuudy https://up.htmlacademy.ru/htmlcss/29/project/technomart#technomart-3-4

2020-09-15 18:54 UTC, raccoonroman commented on catalog.html
> +        <!-- Здесь будет форма сортировки товаров -->
сортировку можно разметить уже сейчас, так как это не форма, а обычные ссылки

2020-09-16 06:53 UTC, HuvosFromDarnassus commented on catalog.html
> +        <a href="">Равшан Джамшутович</a>
Исправлено

2020-09-16 10:26 UTC, raccoonroman approved these changes

2020-09-16 10:26 UTC, merged