Стилизация текста, фона и интерактивных элементов на главной странице
htmlacademy-htmlcss/1367209-technomart-29 pull request #3
Opened 2020-09-19 07:53 UTC by HuvosFromDarnassus

1. Классы html;
2. Подключение шрифтов;
3. Подключение normalize.css
4. Стили текста
5. Стили фонов
6. Состояния интерактивных элементов
7. Все цвета в :root

2020-09-19 19:16 UTC, raccoonroman requested changes
в целом достаточно неплохое именование классов. Так же нужно помнить, что не все свойства нужно брать с фигмы. Некоторые свойства элементы уже имеют по умолчанию, так что нет смысла их им прописывать. Еще есть свойства, которые унаследуют потомки от родителя-элемента - напр, font-family, line-height, color и т. д. Потому это нужно учитывать, чтобы не писать лишние свойства.

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +      <ul class="site-nav">
```suggestion
      <ul class="main-nav-list">
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +        <li class="main-site-nav-item"><a class="main-site-nav-link" href="index.html">Главная</a></li>
```suggestion
        <li class="main-nav-item"><a class="main-nav-link" href="index.html">Главная</a></li>
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +  <main class="container">
контейнер лучше делать отдельным элементом (дивом), так как нет гарантии, что все содержимое в main будет в контейнере и не прилипать к краям. Возможно у какой-нибудь вложенной секции будет фон на всю ширину.
Для универсальности решения контейнер лучше ложить в саму секцию - вот так:
`.some-section>.container>.content`

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +  <main class="container">
тем более по макету видно, что у секции `Сервисы` есть фон на всю ширину

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +        <li class="promo-list-item">
```suggestion
        <li class="promo-item">
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +          <h3 class="promo-list-item-title">Материалы</h3>
```suggestion
          <h3 class="promo-item-title">Материалы</h3>
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +      <ul class="services-toggle-link-list">
```suggestion
      <ul class="services-tabs-list">
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +        <li class="services-toggle-link-list-item"><a class="services-toggle-link" href="">Доставка</a></li>
```suggestion
        <li class="services-tab-item"><a class="services-tab-link" href="">Доставка</a></li>
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +        <li class="services-content-list-item">
```suggestion
        <li class="services-content-item">
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +        <li class="about-list-item">Деловые линии</li>
```suggestion
        <li class="about-item">Деловые линии</li>
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +      <ul class="footer-site-nav">
```suggestion
      <ul class="footer-nav-list">
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +        <li class="footer-site-nav-item"><a class="footer-site-nav-link" href="">Компания</a></li>
```suggestion
        <li class="footer-nav-item"><a class="footer-nav-link" href="">Компания</a></li>
```

2020-09-19 19:16 UTC, raccoonroman commented on index.html
> +          <li class="socials-list-item"><a class="socials-list-link" href="">Вконтакте</a></li>
```suggestion
          <li class="socials-list"><a class="socials-link" href="">Вконтакте</a></li>
```

2020-09-20 08:23 UTC, HuvosFromDarnassus commented on css/style.css
> +    url("../fonts/cuprumitalic.woff") format("woff");
Исправлено

2020-09-20 08:25 UTC, HuvosFromDarnassus commented on css/style.css
> +  font-family: "Cuprum-Regular";
Исправлено

2020-09-20 08:25 UTC, HuvosFromDarnassus commented on css/style.css
> +  font-family: "Cuprum-Bold";
Исправлено

2020-09-20 08:25 UTC, HuvosFromDarnassus commented on css/style.css
> +  font-family: "PT Sans-Regular";
Исправлено

2020-09-20 08:28 UTC, HuvosFromDarnassus commented on css/style.css
> +  min-width: 1220px;
Исправлено

2020-09-20 08:35 UTC, HuvosFromDarnassus commented on css/style.css
> +  font-family: "Cuprum-Regular", Arial, sans-serif;
Исправлено

2020-09-20 08:35 UTC, HuvosFromDarnassus commented on css/style.css
> +  background-color: var(--white);
Исправлено

2020-09-20 08:42 UTC, HuvosFromDarnassus commented on css/style.css
> +  font-family: "Cuprum-Regular";
Исправлено

2020-09-20 08:53 UTC, HuvosFromDarnassus commented on css/style.css
> +  font-size: 14px;
Исправлено

2020-09-20 09:06 UTC, HuvosFromDarnassus commented on css/style.css
> +  font-style: normal;
Исправлено

2020-09-20 09:13 UTC, HuvosFromDarnassus commented on css/style.css
> +  list-style: none;
Исправлено

2020-09-20 09:14 UTC, HuvosFromDarnassus commented on css/style.css
> +.promo-list-item:first-child {
Исправлено

2020-09-20 09:27 UTC, HuvosFromDarnassus commented on index.html
> +      <ul class="site-nav">
Исправлено

2020-09-20 09:32 UTC, HuvosFromDarnassus commented on index.html
> +        <li class="main-site-nav-item"><a class="main-site-nav-link" href="index.html">Главная</a></li>
Исправлено

2020-09-20 09:37 UTC, HuvosFromDarnassus commented on index.html
> +  <main class="container">
Исправлено

2020-09-20 09:40 UTC, HuvosFromDarnassus commented on index.html
> +        <li class="promo-list-item">
Исправлено

2020-09-20 09:45 UTC, HuvosFromDarnassus commented on index.html
> +          <h3 class="promo-list-item-title">Материалы</h3>
Исправлено

2020-09-20 09:45 UTC, HuvosFromDarnassus commented on index.html
> +      <ul class="services-toggle-link-list">
Исправлено

2020-09-20 09:45 UTC, HuvosFromDarnassus commented on index.html
> +        <li class="services-toggle-link-list-item"><a class="services-toggle-link" href="">Доставка</a></li>
Исправлено

2020-09-20 09:46 UTC, HuvosFromDarnassus commented on index.html
> +        <li class="services-content-list-item">
Исправлено

2020-09-20 09:47 UTC, HuvosFromDarnassus commented on index.html
> +        <li class="about-list-item">Деловые линии</li>
Исправлено

2020-09-20 09:47 UTC, HuvosFromDarnassus commented on index.html
> +      <ul class="footer-site-nav">
Исправлено

2020-09-20 09:50 UTC, HuvosFromDarnassus commented on index.html
> +        <li class="footer-site-nav-item"><a class="footer-site-nav-link" href="">Компания</a></li>
Исправлено

2020-09-20 09:51 UTC, HuvosFromDarnassus commented on index.html
> +          <li class="socials-list-item"><a class="socials-list-link" href="">Вконтакте</a></li>
Исправлено

2020-09-20 10:29 UTC, raccoonroman requested changes
В общем, у меня просьба - не пишите лишние стили. Для этого нужно понимать какие свойства наследуются.

2020-09-20 10:29 UTC, raccoonroman commented on css/style.css
> +  font-family: "Cuprum-Italic";
не исправлено, нужно так:
```suggestion
  font-family: "Cuprum";
```

2020-09-20 10:29 UTC, raccoonroman commented on css/style.css
> +  font-family: "Cuprum-BoldItalic";
не исправлено

2020-09-20 10:29 UTC, raccoonroman commented on css/style.css
> +  font-family: "Cuprum-Regular", "Arial", sans-serif;
```suggestion
  font-family: "Cuprum", "Arial", sans-serif;
```

2020-09-20 10:29 UTC, raccoonroman commented on css/style.css
> +  font-family: "Cuprum", "Arial", sans-serif;
для класса `button` уже прописано семейство шрифта

2020-09-20 10:29 UTC, raccoonroman commented on css/style.css
> +  font-family: "Cuprum-Italic", "Arial", sans-serif;
```suggestion
  font-family: "Cuprum", "Arial", sans-serif;
```

2020-09-20 10:29 UTC, raccoonroman commented on css/style.css
> +  font-family: "Cuprum", "Arial", sans-serif;
у всего хедера семейство шрифта Cuprum. Нет смысла для каждого элемента это прописывать. Нужно один раз прописать для хедера и все.

2020-09-20 10:29 UTC, raccoonroman commented on css/style.css
> +  font-family: "Cuprum", "Arial", sans-serif;
нужно просто один раз прописать семейство шрифта для секции `promo` и все. Не нужно будет прописывать для каждого элемента отдельно. Больше об этом говорить не буду.

2020-09-20 10:29 UTC, raccoonroman commented on index.html
> +          <li class="services-tab-list-item"><a class="services-toggle-link" href="">Доставка</a></li>
```suggestion
          <li class="services-tab-item"><a class="services-tab-link" href="">Доставка</a></li>
```

2020-09-20 10:29 UTC, raccoonroman commented on index.html
> +          <li class="socials-list"><a class="socials-link" href="">Вконтакте</a></li>
```suggestion
          <li class="socials-item"><a class="socials-link" href="">Вконтакте</a></li>
```

2020-09-20 11:38 UTC, raccoonroman approved these changes

2020-09-20 11:38 UTC, merged