Сетка на grid & flex
htmlacademy-htmlcss/1367209-technomart-29 pull request #6
Opened 2020-09-28 17:22 UTC by HuvosFromDarnassus

Сделал только сетку и на грида и флексах
Отступы и ширину с высотой для элементов решил пока не делать

2020-09-28 18:43 UTC, raccoonroman requested changes
Я так понимаю, структура самая примерная, которая в последствии будет дополняться и переделываться.
Хорошо, что используешь container, как универсальный элемент для центровки 👍 

Используй border-box для всех элементов. Так удобней рассчитывать значения.
`*, *::before, *::after { box-sizing: border-box; }` 
Есть в исключениях доп. критерия https://up.htmlacademy.ru/htmlcss/29/criteries#d25

2020-09-28 18:43 UTC, raccoonroman commented on css/style.css
> +  grid-template-columns: 1fr max-content;
здесь вполне достаточно флексами обойтись.

2020-09-28 18:43 UTC, raccoonroman commented on css/style.css
> +  justify-self: flex-end;
justify-self: flex-end; лишнее свойство. Вообще свойство justify не так часто используется в реальной жизни как может показаться. Зачастую отступы задаются с помощью маргинов.

2020-09-28 18:43 UTC, raccoonroman commented on css/style.css
> +  grid-template-columns: 1fr 2fr;
табам (кнопкам) лучше задать фиксированную ширину, или ограничить ее. А контенту - все доступное место.

2020-09-28 18:43 UTC, raccoonroman commented on css/style.css
> +  grid-template-columns: 1fr 1fr;
лого должно занимать фиксированную ширину в 220рх, а пункты меню - всю доступную. Но минимальный отступ между ними должен быть, напр. 30рх, как в сетках бутстрапа.

2020-09-28 18:43 UTC, raccoonroman commented on index.html
> +        <div class="user-links-wrapper">
эта обертка лишняя.

2020-09-28 18:43 UTC, raccoonroman commented on index.html
> +            <li class="services-tab-list-item"><a class="services-tab-link" href="">Доставка</a></li>
```suggestion
            <li class="services-tab-item"><a class="services-tab-link" href="">Доставка</a></li>
```

2020-09-29 12:31 UTC, HuvosFromDarnassus commented on css/style.css
> +  grid-template-columns: 1fr max-content;
Исправлено

2020-09-29 12:32 UTC, HuvosFromDarnassus commented on css/style.css
> +  justify-self: flex-end;
Исправлено

2020-09-29 12:36 UTC, HuvosFromDarnassus commented on css/style.css
> +  grid-template-columns: 1fr 2fr;
Исправлено

2020-09-29 13:00 UTC, HuvosFromDarnassus commented on css/style.css
> +  grid-template-columns: 1fr 1fr;
Исправлено

2020-09-29 13:01 UTC, HuvosFromDarnassus commented on index.html
> +        <div class="user-links-wrapper">
Исправление

2020-09-29 13:03 UTC, HuvosFromDarnassus commented on index.html
> +            <li class="services-tab-list-item"><a class="services-tab-link" href="">Доставка</a></li>
Исправлено

2020-09-29 18:50 UTC, raccoonroman approved these changes

2020-09-29 18:50 UTC, merged