Отступы и размеры в проекте
htmlacademy-htmlcss/1367209-technomart-29 pull request #7
Opened 2020-10-02 14:15 UTC by HuvosFromDarnassus

- Проверил макет в pixel perfect, увидел несовпадения, хочу проверить если какие-то ошибки на данном этапе

2020-10-02 18:39 UTC, raccoonroman requested changes
1) https://up.htmlacademy.ru/htmlcss/28/examples_overflow#technomart
2) Карточки должны быть одинаковой высоты https://prnt.sc/us2hy8
3) Почитай про object-fit и где его можно применить https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  height: 164px;
что если картинка будет других пропорций или размеров. Изображение может исказиться. Это нужно учивывать.

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  height: 145px;
нужно задавать внутренний оступ, чтобы большое изображение не прилипало к краям.

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  width: 394px;
на будущее: когда делается адаптивный сайт вместо width нужно использовать max-width

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  padding: 13px 22px;
это правильно, что отступы слева и справа одинаковые 👍

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  top: 50%;
чтобы элемент был ровно по центру по вертикали нужно использовать еще свойство `transform: translateY(-50%);` 
_Будет заметно для больших элементов_

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  left: 0px;
если значение 0, `px` можно не писать

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  width: 220px;
https://prnt.sc/us2o0r
при переполнении текст не должен прилипать к краям

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  padding: 0;
> padding: 0;

свойство лишнее

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  height: 68px;
вместо высоты пропиши для изображения логотипа `display: block;`

2020-10-02 18:39 UTC, raccoonroman commented on css/style.css
> +  position: absolute;
меню абсолютом точно не нужно делать https://prnt.sc/us2xwv, оно должно быть в общем потоке

2020-10-02 18:39 UTC, raccoonroman commented on index.html
> +        <div class="user-links-wrapper">
обертка лишняя

2020-10-03 08:26 UTC, HuvosFromDarnassus commented on css/style.css
> +  text-align: center;
Исправлено

2020-10-03 08:27 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding-right: 14px;
Исправлено

2020-10-03 08:28 UTC, HuvosFromDarnassus commented on css/style.css
> +  height: 42px;
Исправлено

2020-10-03 08:29 UTC, HuvosFromDarnassus commented on css/style.css
> +  height: 42px;
Исправлено

2020-10-03 08:30 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding: 9px 19px;
Исправлено

2020-10-03 08:51 UTC, HuvosFromDarnassus commented on css/style.css
> +  align-items: stretch;
Исправлено

2020-10-03 08:52 UTC, HuvosFromDarnassus commented on css/style.css
> +  height: min-content;
Испрвлено

2020-10-03 08:52 UTC, HuvosFromDarnassus commented on css/style.css
> +  margin-top: 7px;
Исправлено

2020-10-03 08:53 UTC, HuvosFromDarnassus commented on css/style.css
> +  height: min-content;
Исправлено

2020-10-03 09:09 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding: 16px 54px;
Исправлено

2020-10-03 09:11 UTC, HuvosFromDarnassus commented on css/style.css
> +  margin-top: 59px;
Исправлено

2020-10-03 09:12 UTC, HuvosFromDarnassus commented on css/style.css
> +  margin: 0;
Исправлено

2020-10-03 09:32 UTC, HuvosFromDarnassus commented on css/style.css
> +  width: 135px;
Исправлено

2020-10-03 09:42 UTC, HuvosFromDarnassus commented on css/style.css
> +  outline: 1px var(--basic-background) solid;
Исправлено

2020-10-03 09:42 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding-bottom: 21px;
Исправлено

2020-10-03 09:44 UTC, HuvosFromDarnassus commented on css/style.css
> +  height: 164px;
Исправлено

2020-10-03 09:52 UTC, HuvosFromDarnassus commented on css/style.css
> +  height: 145px;
Исправлено

2020-10-03 09:53 UTC, HuvosFromDarnassus commented on css/style.css
> +  width: 394px;
Исправил

2020-10-03 09:56 UTC, HuvosFromDarnassus commented on css/style.css
> +  top: 50%;
Исправлено

2020-10-03 09:56 UTC, HuvosFromDarnassus commented on css/style.css
> +  left: 0px;
Исправлено

2020-10-03 10:05 UTC, HuvosFromDarnassus commented on css/style.css
> +  width: 220px;
Исправлено

2020-10-03 10:06 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding: 0;
Исправлено

2020-10-03 10:16 UTC, HuvosFromDarnassus commented on css/style.css
> +  height: 68px;
Исправлено

2020-10-03 11:04 UTC, HuvosFromDarnassus commented on css/style.css
> +  position: absolute;
Исправлено

2020-10-03 11:05 UTC, HuvosFromDarnassus commented on index.html
> +        <div class="user-links-wrapper">
Исправлено

2020-10-03 19:09 UTC, raccoonroman requested changes

2020-10-03 19:09 UTC, raccoonroman commented on css/style.css
> +  max-height: 68px;
> max-height: 68px;

Что-то в коде не так, если такое написано :) Это свойство не рекомендуется к использованию, так как нужно учитывать переполнение.

2020-10-03 19:09 UTC, raccoonroman commented on css/style.css
> +  margin-top: -35px;
> margin-top: -35px;

что-то в коде не так, нужно исправлять

2020-10-03 19:09 UTC, raccoonroman commented on index.html
> +      <a class="footer-logo" href="index.html"><img src="https://via.placeholder.com/220x68" alt="Логотип" /></a>
уже можно вставлять изображение :)

2020-10-04 08:29 UTC, HuvosFromDarnassus commented on css/style.css
> +  min-height: 47px;
Исправлено

2020-10-04 08:32 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding: 18.5px 27px;
Исправлено

2020-10-04 08:42 UTC, HuvosFromDarnassus commented on css/style.css
> +  gap: 17px;
Исправлно

2020-10-04 08:56 UTC, HuvosFromDarnassus commented on css/style.css
> +  min-height: 164px;
Исправлено

2020-10-04 09:14 UTC, HuvosFromDarnassus commented on css/style.css
> +  max-height: 68px;
Исправлено

2020-10-04 09:20 UTC, HuvosFromDarnassus commented on css/style.css
> +  margin-top: -35px;
Исправлено

2020-10-04 17:58 UTC, raccoonroman requested changes
Осталось немного

2020-10-04 17:58 UTC, raccoonroman commented on css/style.css
> +  max-height: 42px;
это лишнее свойсво, которое не нужно использовать. Для верстки оно доставляет лишние проблемы. Я не понимаю, почему ты его не убираешь.

2020-10-04 17:58 UTC, raccoonroman commented on css/style.css
> +  max-height: 42px;
то же самое. Самый оптимальный вариант, чтобы вывести темно-красную полосу под логотипом - это использовать псевдоэлемент с абсолютным позиционированием. Тогда не придется ограничивать ширину для хедера.

2020-10-04 17:58 UTC, raccoonroman commented on css/style.css
> +  max-height: 164px;
можно размеры задавать без `max-` если используется `object-fit: contain;`

2020-10-04 17:58 UTC, raccoonroman commented on css/style.css
> +  min-height: 135px;
вот что будет, если загрузить большое изображение https://prnt.sc/ut0449
Здесь размеры нужно задавать фиксированные, так как внутри не текстовое содержимое, а картинка, которая сама будет подстраиваться под доступную область.
Вот как бы я сделал: 
1) https://prnt.sc/ut07gc ширина ссылке не нужна, высота фиксированная, паддинг чуть больше. 
2) https://prnt.sc/ut07wc для картинки object-fit: contain; и max-height: 100%;

Тогда при любом размере изображения, оно будет смотреться адекватно.

2020-10-05 09:45 UTC, HuvosFromDarnassus commented on css/style.css
> +  max-height: 42px;
Исправлено

2020-10-05 10:09 UTC, HuvosFromDarnassus commented on css/style.css
> +  max-height: 42px;
Исправлено

2020-10-05 10:11 UTC, HuvosFromDarnassus commented on css/style.css
> +  max-height: 164px;
Исправлено

2020-10-05 10:16 UTC, HuvosFromDarnassus commented on css/style.css
> +  min-height: 135px;
Исправлено

2020-10-05 10:40 UTC, raccoonroman approved these changes
👍

2020-10-05 10:40 UTC, raccoonroman commented on css/style.css
> +  content: "";
общие стили для логотипа можно вынести в общий класс

2020-10-05 10:41 UTC, merged