Сетка, отступы и размеры на странице каталога
htmlacademy-htmlcss/1367209-technomart-29 pull request #8
Opened 2020-10-09 15:59 UTC by HuvosFromDarnassus

2020-10-09 19:58 UTC, raccoonroman requested changes

2020-10-09 19:58 UTC, raccoonroman commented on css/style.css
> +  top: 45%;
```suggestion
  top: 50%;
  transform: translateY(-50%);
```

2020-10-09 19:58 UTC, raccoonroman commented on css/style.css
> +  top: 45%;
этот разделитель (точка) не относится конкретно к `personal-area`, а просто служит разделителем между пунктами. При наведении на него не должна подсвечиваться ссылка. Сделай ссылки навигации пользователя списком, где у каждой лишки будет этот разделитель (псевдоэлемент), кроме последней.

2020-10-09 19:58 UTC, raccoonroman commented on css/style.css
> +  margin-top: 20px;
лучше хлебным крошкам задать сверху и снизу паддинг. Тогда элементы будут всегда иметь свои внутренние отступы и не зависеть от внешнего окружения. Можно будет спокойно их взять и вставить в любое другое место.

2020-10-09 19:58 UTC, raccoonroman commented on css/style.css
> +  grid-template-rows: 1fr 1fr 1fr;
кол-во рядов не нужно указывать, их может быть сколько угодно.

2020-10-09 19:58 UTC, raccoonroman commented on css/style.css
> +  margin-top: 50px;
здесь не верхний маргин описанию нужно задать, а нижний паддинг каталогу с товарами. Опять же, чтобы не завязывать один блок на другой. А если надо будет удалить это описание? https://prnt.sc/uwdftn Придется править отступы. А такого быть не должно.

2020-10-10 13:43 UTC, HuvosFromDarnassus commented on css/style.css
> +  top: 45%;
Исправлено

2020-10-10 13:50 UTC, HuvosFromDarnassus commented on css/style.css
> +  margin-top: 20px;
Исправлено

2020-10-10 13:51 UTC, HuvosFromDarnassus commented on css/style.css
> +  grid-template-rows: 1fr 1fr 1fr;
Исправлено

2020-10-10 13:58 UTC, HuvosFromDarnassus commented on css/style.css
> +  margin-top: 50px;
Исправлено

2020-10-10 16:09 UTC, raccoonroman commented on catalog.html
> +        <ul class="list-reset orders-personal-list">
```suggestion
        <ul class="list-reset user-nav-list">
```

2020-10-10 16:09 UTC, raccoonroman commented on catalog.html
> +          <li class="personal-list-item"><a class="personal-area" href="">Личный кабинет</a></li>
стилизация у пунктов одинаковая, соответственно, классы должны быть одинаковые

2020-10-10 16:10 UTC, merged