Декоративные элементы на главной странице
htmlacademy-htmlcss/1367209-technomart-29 pull request #9
Opened 2020-10-16 07:55 UTC by HuvosFromDarnassus

- Решил сделать промежуточный ПР, чтобы в случае ошибок сразу исправить
- Проект пока не совпадает по pixel perfect

2020-10-16 20:32 UTC, raccoonroman requested changes

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  content: "New";
метку `New`нужно добавлять по класу. То есть, например, в первой карточки класc new, соответственно, отображается красная ленточка. Если добавить этот класс на любую другую карточку, то там тоже должны появиться эти ленточки. Ведь эта ленточка может быть не только в первой карточки, а в любой другой.

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  position: relative;
общие стили в общий класс

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  height: 218px;
высоту не нужно ограничивать, да и она здесь не нужна

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  height: 218px;
я конечно, понимаю, почему ты ее прописал. Это как раз таки яркий пример того, почему лучше использовать `box-sizing: border-box;`

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  transform: rotate(45deg);
сделай по аналогии, где у top и right одинаковые значения

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  content: "New";
метку New должны иметь не 2-й и 4-й товары, а `Перфоратор BOSCH BFG 3000` и `Перфоратор BOSCH BFG 2000`

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  padding: 36px 0 29px 0;
```suggestion
  padding: 36px 0 29px;
```

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  margin-right: 5px;
У последнего элемента маргин нужно обнулять https://habr.com/ru/post/340420/

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  border-radius: 50%;
border-radius нужен только ссылке, здесь не нужен

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  box-shadow: 0 10px 10px rgba(0, 0, 0, 0.3);
цвет нужно вынести в кастомное свойство, не забывай

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  background-image: url("img/pattern-light.jpg");
не понимаю, что это за картинка и зачем она нужна

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  justify-content: space-around;
сами пункты формы лучше сделать списком с 3х элементов:
1) Имя Фамилия
2) емаил
3) текст письма.
Не нужны будут обертки, это делается удобно с помощью гридов

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +.write-us-message-label {
стили у лейблов абсолютно одинаковые, им не нужны разные классы

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +.write-us-input-mail {
у инпутов классы тоже должны быть одинаковые

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  min-width: 200px;
минимальная ширина не нужна в данном случае

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  padding: 7px 8px 7px 12px;
слева и справа паддинг сделай одинаковый

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  padding: 37px 0 37px;
слева и справа добавь паддинг, а кнопке внутри можно задать ширину 100%

2020-10-16 20:32 UTC, raccoonroman commented on css/style.css
> +  margin: auto auto;
```suggestion
  margin: auto;
```

2020-10-16 20:32 UTC, raccoonroman commented on index.html
> +        <p class="write-us-name-wrapper">
обертки убрать, сделать списком

2020-10-16 20:32 UTC, raccoonroman commented on index.html
> +          <input class="write-us-input-mail" id="write-us-mail" type="mail" name="mail" placeholder="email@example.com">
```suggestion
          <input class="write-us-input-mail" id="write-us-mail" type="email" name="mail" placeholder="email@example.com">
```

2020-10-17 07:20 UTC, HuvosFromDarnassus commented on catalog.html
> +            <div class="search-wrapper"><input class="main-search" type="text" placeholder="Поиск:"></div>
Исправлено

2020-10-17 07:26 UTC, HuvosFromDarnassus commented on catalog.html
> +                  xmlns="http://www.w3.org/2000/svg">
Исправлено

2020-10-17 07:27 UTC, HuvosFromDarnassus commented on index.html
> +        <div class="logo-search-wrapper">
Исправлено

2020-10-17 07:31 UTC, HuvosFromDarnassus commented on css/style.css
> +  background-image: url(/img/icon-search.svg);
Исправлено

2020-10-17 07:52 UTC, HuvosFromDarnassus commented on css/style.css
> +  content: "";
Исправлено

2020-10-17 07:57 UTC, HuvosFromDarnassus commented on css/style.css
> +  transform: translateY(75%);
Сделал иконку кнопкой, само правильно встало)

2020-10-17 07:58 UTC, HuvosFromDarnassus commented on css/style.css
> +  min-width: 229px;
Исправлено

2020-10-17 07:59 UTC, HuvosFromDarnassus commented on css/style.css
>  .user-links-wrapper {
Исправлено

2020-10-17 08:00 UTC, HuvosFromDarnassus commented on css/style.css
> +  transform: translateY(35%);
Исправлено

2020-10-17 08:01 UTC, HuvosFromDarnassus commented on css/style.css
> +  transform: translateY(70%);
Исправлено

2020-10-17 08:01 UTC, HuvosFromDarnassus commented on css/style.css
> +  transform: translateY(90%);
Исправлено

2020-10-17 08:04 UTC, HuvosFromDarnassus commented on css/style.css
> +  right: -25px;
Исправлено

2020-10-17 08:30 UTC, HuvosFromDarnassus commented on css/style.css
> +  position: absolute;
Исправлено

2020-10-17 08:31 UTC, HuvosFromDarnassus commented on css/style.css
> +  overflow: hidden;
Исправлено

2020-10-19 09:23 UTC, HuvosFromDarnassus commented on css/style.css
> +  overflow: hidden;
Исправлено

2020-10-19 15:14 UTC, HuvosFromDarnassus commented on css/style.css
> +  content: "New";
Исправлено

2020-10-19 15:15 UTC, HuvosFromDarnassus commented on css/style.css
> +  position: relative;
Исправлено

2020-10-19 15:47 UTC, HuvosFromDarnassus commented on css/style.css
> +  height: 218px;
Исправлено

2020-10-19 15:48 UTC, HuvosFromDarnassus commented on css/style.css
> +  transform: rotate(45deg);
Исправлено

2020-10-19 15:49 UTC, HuvosFromDarnassus commented on css/style.css
> +  content: "New";
Исправлено

2020-10-19 15:51 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding: 36px 0 29px 0;
Исправлено

2020-10-19 15:52 UTC, HuvosFromDarnassus commented on css/style.css
> +  margin-right: 5px;
Исправлено

2020-10-19 15:53 UTC, HuvosFromDarnassus commented on css/style.css
> +  border-radius: 50%;
Исправлено

2020-10-19 15:56 UTC, HuvosFromDarnassus commented on css/style.css
> +  box-shadow: 0 10px 10px rgba(0, 0, 0, 0.3);
Исправлено

2020-10-19 15:58 UTC, HuvosFromDarnassus commented on css/style.css
> +  background-image: url("img/pattern-light.jpg");
Это небольшое затенение у табов в .services

2020-10-20 07:44 UTC, HuvosFromDarnassus commented on css/style.css
> +.write-us-message-label {
Исправлено

2020-10-20 07:45 UTC, HuvosFromDarnassus commented on css/style.css
> +.write-us-input-mail {
Исправлено

2020-10-20 08:26 UTC, HuvosFromDarnassus commented on css/style.css
> +  justify-content: space-around;
Исправлено

2020-10-20 08:26 UTC, HuvosFromDarnassus commented on css/style.css
> +  min-width: 200px;
Исправлено

2020-10-20 08:26 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding: 7px 8px 7px 12px;
Исправлено

2020-10-20 08:28 UTC, HuvosFromDarnassus commented on css/style.css
> +  padding: 37px 0 37px;
Исправлено

2020-10-20 08:28 UTC, HuvosFromDarnassus commented on css/style.css
> +  margin: auto auto;
Исправлено

2020-10-20 08:28 UTC, HuvosFromDarnassus commented on index.html
> +        <p class="write-us-name-wrapper">
Исправлено

2020-10-20 08:29 UTC, HuvosFromDarnassus commented on index.html
> +          <input class="write-us-input-mail" id="write-us-mail" type="mail" name="mail" placeholder="email@example.com">
Исправлено

2020-10-21 18:13 UTC, raccoonroman requested changes

2020-10-21 18:13 UTC, raccoonroman commented on index.html
> +          <input class="main-search" type="text" placeholder="Поиск:">
пока это пропускаю, на задание про формы нужно будет исправить

2020-10-21 18:13 UTC, raccoonroman commented on index.html
> +            <span class="new-product-mark">New</span>
смотри, раньше у тебя метка NEW выводилась через псевдоэлемент. Было все нормально. Сейчас же ты выводишь тег с текстом там где этого делать не нужно. Все, что нужно было сделать, это вместо `.popular-products-item:nth-child(2) .product-card::before {}` или как там было, я не помню, прописать вот так: `.product-card.new::before {}` То есть, если у какой-то карточки есть метка `new`, то все что нужно сделать, это добавить для `product-card` класс `new`. А в разметке убери эти теги с new.

2020-10-21 18:13 UTC, raccoonroman commented on index.html
> +                  d="M15.54 11.73c.92-.3 2.1 1.91 3.35 2.75.95.64 1.67.5 1.67.5l3.34-.04s1.75-.1.92-1.46c-.07-.11-.48-1-2.49-2.83-2.1-1.92-1.8-1.6.72-4.92C24.58 3.71 25.2 2.48 25 1.95c-.19-.5-1.32-.3
если свг заменил на img, то все эти path-ы нужно убрать

2020-10-21 18:13 UTC, raccoonroman commented on index.html
> +        <li class="write-us-mail-item">
у лишек должна стилизация быть одинаковая и классы соответственно тоже

2020-10-22 11:01 UTC, HuvosFromDarnassus commented on catalog.html
> +            <div class="search-wrapper"><input class="main-search" type="text" placeholder="Поиск:"></div>
Исправлено #2

2020-10-22 11:19 UTC, HuvosFromDarnassus commented on css/style.css
> +  content: "New";
Исправлено #2

2020-10-22 13:49 UTC, HuvosFromDarnassus commented on css/style.css
> +  background-image: url("img/pattern-light.jpg");
Не внимательность, я скопировал пару строк с разбором барбершопа, там паттерн использовался. **Исправлено**

2020-10-22 13:53 UTC, HuvosFromDarnassus commented on css/style.css
> +.logo-search-wrapper {
Исправлено

2020-10-23 07:38 UTC, HuvosFromDarnassus commented on css/style.css
> +  background-image: url("../img/slider-img-1.jpg");
Исправлено

2020-10-23 07:40 UTC, HuvosFromDarnassus commented on css/style.css
> +  transform: translateY(-50%);
Исправлено

2020-10-23 07:49 UTC, HuvosFromDarnassus commented on index.html
> +            <span class="new-product-mark">New</span>
Вот это круто, так не умел. Исправлено

2020-10-23 07:51 UTC, HuvosFromDarnassus commented on index.html
> +                  d="M15.54 11.73c.92-.3 2.1 1.91 3.35 2.75.95.64 1.67.5 1.67.5l3.34-.04s1.75-.1.92-1.46c-.07-.11-.48-1-2.49-2.83-2.1-1.92-1.8-1.6.72-4.92C24.58 3.71 25.2 2.48 25 1.95c-.19-.5-1.32-.3
Исправлено

2020-10-23 07:53 UTC, HuvosFromDarnassus commented on index.html
> +        <li class="write-us-mail-item">
Исправлено

2020-10-23 09:00 UTC, raccoonroman approved these changes

2020-10-23 09:01 UTC, merged